version: "3.4"

services:
  web:
    build: .
    ports:
      - "127.0.0.1:8000:80"
    environment:
      DATABASE_URL: mysql://user:password@database:3306/symfony?serverVersion=8&charset=utf8mb4
      APP_ENV: dev
    depends_on:
      database:
        condition: service_healthy
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www
        - action: rebuild
          path: package.json
        - action: rebuild
          path: composer.json

  database:
    image: mysql/mysql-server
    healthcheck:
      test: [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-prootpassword",
        ] # Command to check health.
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s
    #        container_name: database
    volumes:
      - ./database-setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"

volumes:
  db-data:
    name: database
